### ISSUE TITLE
AppTableField 实体与接口返回的JSON结构不一致

### ISSUE THREAD

**Issue by Yunie9** [larksuite/oapi-sdk-java#87]
AppTableField 实体 description 字段类型为 AppTableFieldDescription，但是列出表格字段接口返回的 description 为字符串，导致反序列化报错：
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2670 path $.data.items[9].description
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.lark.oapi.core.utils.UnmarshalRespUtil.unmarshalResp(UnmarshalRespUtil.java:22)
	at com.lark.oapi.service.bitable.v1.BitableService$AppTableField.list(BitableService.java:1721)

**Comment by zhouzhaojie** [comment]
我也遇到了，有没有临时解决方案

**Comment by Yunie9** [comment]
@zhouzhaojie 只能把代码拉下来自己修改源码了

**Comment by szw-yunie** [comment]
@zhouzhaojie 找到解决办法了，以下飞书官方工作人员，描述信息是通过请求参数的text_field_as_array控制，如果不填写这个参数那么默认返回的就是字符串。只要把在请求里面吧text_field_as_array设置为true，这个字段返回的就是一个数组，结构就对得上了

**Comment by Yunie9** [comment]
@zhouzhaojie 找到解决办法了，问了飞书官方工作人员，描述信息是通过请求参数的text_field_as_array控制，如果不填写这个参数那么默认返回的就是字符串。只要把在请求里面把text_field_as_array设置为true，这个字段返回的就是一个数组，结构就对得上了

**Comment by Hai-Long-Wang** [comment]
> @zhouzhaojie找到解决办法了，问了飞书官方工作人员，描述信息是通过请求参数的text_field_as_array控制，如果不填这个参数那么默认返回的就是字符串。只需要把在请求里面把text_field_as_array设置为true，这一段返回的就是一个数组，结构就对得上了

您好，请问一下您这边设置textFieldAsArray(true)之后不会报错了吗？我这边貌似设置了仍然会有反序列化错误，
